# Generated by Django 4.1 on 2022-08-29 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='contactModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('mob', models.CharField(max_length=40)),
                ('email', models.EmailField(max_length=120)),
                ('msg', models.CharField(max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='loginModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aid', models.CharField(max_length=120)),
                ('passwd', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='regModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
                ('course', models.CharField(max_length=70)),
                ('gender', models.CharField(max_length=60)),
                ('mob', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=120)),
                ('passwd', models.CharField(max_length=80)),
                ('add', models.CharField(max_length=120)),
                ('profile', models.FileField(upload_to='static/profile/')),
            ],
        ),
    ]
