# Generated by Django 4.1 on 2022-09-02 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='loginModel',
            new_name='SigninModel',
        ),
    ]
