# Generated by Django 4.1 on 2022-09-03 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0002_rename_loginmodel_signinmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='myregModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
                ('course', models.CharField(max_length=70)),
                ('gender', models.CharField(max_length=60)),
                ('mob', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=120)),
                ('passwd', models.CharField(max_length=80)),
                ('add', models.CharField(max_length=120)),
                ('city', models.CharField(max_length=120)),
            ],
        ),
        migrations.DeleteModel(
            name='regModel',
        ),
    ]
